FROM rapidsai/miniforge-cuda:cuda11.8.0-base-ubuntu22.04-py3.9

RUN chmod -R 777 /opt/conda

# Create user analysis
RUN useradd -m hcs_analysis

# switch user to analysis
USER hcs_analysis

# Update base conda env with conda-env yaml file
COPY environment_fractal.yml /home/hcs_analysis/environment.yml
RUN conda env update -n base -f /home/hcs_analysis/environment.yml