name: base 
channels:
  - conda-forge
  - defaults
  - rapidsai
dependencies:
  - numpy=1.24.4
  - pandas=2.2.1
  - cucim=23.6.0
  - cudatoolkit=11.8
  - scikit-image=0.20.0
  - pip
  - pip:
      - cellpose>=3
      - openpyxl==3.1.2
      - imagecodecs==2024.1.1
      - aicsimageio==4.14.0
      - fire==0.5.0
      - numba==0.59.0
      - ome-zarr==0.8.0