---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "bioinfotongli_basictransform"
description: Apply BaSiC models to correct illumination in multi-dimensional images
keywords:
  - illumination correction
  - imaging
  - image analysis
tools:
  - "bioinfotongli":
      description: ""
      homepage: ""
      documentation: ""
      tool_dev_url: ""
      doi: ""
      licence: 

input:
  - meta:
      type: dict 
      description: meta data of the zarr file
      pattern: ""

  - fov:
      type: int 
      description: Field of View of one well or one slide
      pattern: "[0..9]+"

  - zarr_root:
      type: folder
      description: ome-ngff zarr root folder
      pattern: "*.zarr"

  - field:
      type: int 
      description: position index of the image stack; HCS data only; -1 for WSI data
      pattern: "0..4 or -1"

  - models:
      type: folder 
      description: BaSiC models
      pattern: ""

   - new_zarr_root:
      type: folder
      description: ome-ngff zarr root folder where the transformed images will be saved 
      pattern: "*.zarr"

output:
   - meta:
      type: dict 
      description: meta data of the zarr file
      pattern: " "
  
- expected_dir:
      type: folder 
      description: the FOV folder containing the transformed images
      pattern: " "

  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@BioinfoTongLI"
maintainers:
  - "@BioinfoTongLI"
