---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "bioinfotongli_basicfitting"
description: A wrapper of BaSiC for fitting illumination correction models to multi-dimensional images
keywords:
  - illumination correction
  - imaging
  - image analysis
tools:
  - "bioinfotongli":
      description: ""
      homepage: ""
      documentation: ""
      tool_dev_url: ""
      doi: ""
      licence: 

input:
  - meta:
      type: dict 
      description: meta data of the zarr file
      pattern: ""

  - zarr_root:
      type: folder
      description: ome-ngff zarr root folder
      pattern: "*.zarr"

  - field:
      type: int 
      description: position index of the image stack; HCS data only; -1 for WSI data
      pattern: "0..4 or -1"

  - C:
      type: int 
      description: channel index of the image stack
      pattern: "0"

   - T:
      type: int 
      description: time index of the image stack
      pattern: "0"

output:
  - meta:
      type: dict 
      description: meta data of the zarr file
      pattern: ""

  - field:
      type: int 
      description: position index of the image stack; HCS data only; -1 for WSI data
      pattern: "0..4 or -1"
  
  - basic_models:
      type: folder 
      description: "Position index & Basic models dir containing the fitted models"
      pattern: "BaSiC_model_C*_P0_T*"

  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@BioinfoTongLI"
maintainers:
  - "@BioinfoTongLI"
